#!/usr/bin/env bash

# Original source from: https://gist.github.com/jordan-brough/48e2803c0ffa6dc2e0bd

# Download this script as "git-recent" (no extension), chmod it to be executable and put it in your
# path somewhere (e.g. /usr/bin). You can then use it via `git recent` from inside any git repo.

# Examples:

# Interactive prompt for most recent 4 branches:
#   $ git recent -n 5
#   1) master  4) deleted-branch
#   2) stable  5) improve-everything
#   3) fun
#   Choose a branch: 2

# List mode (non-interactive):
#   $ git recent -n 5 -l
#   master
#   stable
#   fun
#   deleted-branch
#   improve-everything

# Verify branch existence:
#   $ git recent -n 5 -l -e
#   master
#   stable
#   fun
#   improve-everything
#   something-else
#   # (notice "deleted-branch" removed from results)

# Contributors:
#   - jordan-brough
#   - fritz-c

usage()
{
  echo "usage: git recent [-n lines] [-l] [-e]"
}

while getopts "hn:le" opt; do
  case $opt in
    h) # help
      usage
      exit 1
      ;;
    n) # number of results
      NUM=$OPTARG
      ;;
    \?)
      usage
      exit 1
      ;;
  esac
done


CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD);
BRANCHES=(
  $(git reflog |
    egrep -io "moving from ([^[:space:]]+)" |
    awk '{ print $3 }' | # extract 3rd column
    awk ' !x[$0]++' | # Removes duplicates.  See http://stackoverflow.com/questions/11532157
    egrep -v '^[a-f0-9]{40}$' | # remove hash results
    while read line; do # verify existence
      git rev-parse --verify "$line" &>/dev/null && [[ $line != $CURRENT_BRANCH ]] && echo "$line"
    done
  )
)

GREEN=$(tput setaf 2)
normal=$(tput sgr0)

printf "${GREEN}* $CURRENT_BRANCH${normal}\n"
printf '%s\n' "${BRANCHES[@]}"
